### ISSUE TITLE
reveal.el

### ISSUE THREAD

**Issue by unhammer** [erickgnavar/cloak-mode#1]
Hi, not really an issue, just a heads-up if you haven't looked into reveal.el, it's built-in to emacs and allows revealing text at point that has been hidden using overlays. Could probably be used in conjunction with this :-) 

(Try making a ~/.authinfo file to see how it works in M-x authinfo-mode)

**Comment by erickgnavar** [comment]
Hi, didn't know about that package, I'll take a look to it, thanks :)
