### ISSUE TITLE
Q. How to setup multiple patterns per mode?

### ISSUE THREAD

**Issue by grafov** [erickgnavar/cloak-mode#2]
I stucked with restriction that mentioned in the help for `cloack-mode-patterns` variable: "Patterns should only have one capturing group (())." How to avoid it? How to handle for example such things:

```
APP_TOKEN=secret
SOMETHAT_PASSWORD=secret
```
I want to hide both that have "token" or "password" in the end of name. I tried regexps like these:
```
TOKEN[\s\t]*=[\s\t]*\\(.*\\)$\\|PASSWORD[\s\t]*=[\s\t]*\\(.*\\)$
TOKEN\\|PASSWORD[\s\t]*=[\s\t]*\\(.+\\)$
```
The first matches only PASSWORD string, the second doesn't work at all. I don't understand how to avoid restriction and match multiple such string for a single mode :(

It would be helpful to add more examples to documentation.

Anyway thank you for this mode. It could be very useful for online demonstrations.

**Comment by erickgnavar** [comment]
I added support to have multiple patterns per mode, there are now examples about defining the patterns in both cases in the README

> Anyway thank you for this mode. It could be very useful for online demonstrations.

That's was the reason to make this package, I didn't want to leak sensitive data while presenting my screen 😅

Sorry for the late response 😅
